/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ExerciceListeRouteImport } from './routes/exercice-liste'
import { Route as ExerciceIntroRouteImport } from './routes/exercice-intro'
import { Route as ExerciceRouteImport } from './routes/exercice'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursLettresRouteImport } from './routes/cours.lettres'
import { Route as CoursFamilyRouteImport } from './routes/cours.$family'
import { Route as AppReglagesRouteImport } from './routes/_app.reglages'
import { Route as AppPlusRouteImport } from './routes/_app.plus'
import { Route as AppMonProfilRouteImport } from './routes/_app.mon-profil'
import { Route as AppCommunauteRouteImport } from './routes/_app.communaute'
import { Route as AppBibliothequeRouteImport } from './routes/_app.bibliotheque'
import { Route as AppAccueilRouteImport } from './routes/_app.accueil'
import { Route as ExerciceSyllabesConsonantRouteImport } from './routes/exercice.syllabes.$consonant'
import { Route as ExerciceMotsGroupIdRouteImport } from './routes/exercice.mots.$groupId'
import { Route as ExerciceMotsCroisesPuzzleIdRouteImport } from './routes/exercice.mots-croises.$puzzleId'
import { Route as ExerciceLettreCharRouteImport } from './routes/exercice.lettre.$char'
import { Route as CoursSyllabesConsonantRouteImport } from './routes/cours.syllabes.$consonant'
import { Route as CoursMotsGroupIdRouteImport } from './routes/cours.mots.$groupId'
import { Route as CoursLettresCharRouteImport } from './routes/cours.lettres.$char'
import { Route as CoursLettresFormationCharRouteImport } from './routes/cours.lettres.formation.$char'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciceListeRoute = ExerciceListeRouteImport.update({
  id: '/exercice-liste',
  path: '/exercice-liste',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciceIntroRoute = ExerciceIntroRouteImport.update({
  id: '/exercice-intro',
  path: '/exercice-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciceRoute = ExerciceRouteImport.update({
  id: '/exercice',
  path: '/exercice',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursLettresRoute = CoursLettresRouteImport.update({
  id: '/cours/lettres',
  path: '/cours/lettres',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursFamilyRoute = CoursFamilyRouteImport.update({
  id: '/cours/$family',
  path: '/cours/$family',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReglagesRoute = AppReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => AppRoute,
} as any)
const AppPlusRoute = AppPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => AppRoute,
} as any)
const AppMonProfilRoute = AppMonProfilRouteImport.update({
  id: '/mon-profil',
  path: '/mon-profil',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunauteRoute = AppCommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliothequeRoute = AppBibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => AppRoute,
} as any)
const AppAccueilRoute = AppAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AppRoute,
} as any)
const ExerciceSyllabesConsonantRoute =
  ExerciceSyllabesConsonantRouteImport.update({
    id: '/syllabes/$consonant',
    path: '/syllabes/$consonant',
    getParentRoute: () => ExerciceRoute,
  } as any)
const ExerciceMotsGroupIdRoute = ExerciceMotsGroupIdRouteImport.update({
  id: '/mots/$groupId',
  path: '/mots/$groupId',
  getParentRoute: () => ExerciceRoute,
} as any)
const ExerciceMotsCroisesPuzzleIdRoute =
  ExerciceMotsCroisesPuzzleIdRouteImport.update({
    id: '/mots-croises/$puzzleId',
    path: '/mots-croises/$puzzleId',
    getParentRoute: () => ExerciceRoute,
  } as any)
const ExerciceLettreCharRoute = ExerciceLettreCharRouteImport.update({
  id: '/lettre/$char',
  path: '/lettre/$char',
  getParentRoute: () => ExerciceRoute,
} as any)
const CoursSyllabesConsonantRoute = CoursSyllabesConsonantRouteImport.update({
  id: '/cours/syllabes/$consonant',
  path: '/cours/syllabes/$consonant',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursMotsGroupIdRoute = CoursMotsGroupIdRouteImport.update({
  id: '/cours/mots/$groupId',
  path: '/cours/mots/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursLettresCharRoute = CoursLettresCharRouteImport.update({
  id: '/$char',
  path: '/$char',
  getParentRoute: () => CoursLettresRoute,
} as any)
const CoursLettresFormationCharRoute =
  CoursLettresFormationCharRouteImport.update({
    id: '/formation/$char',
    path: '/formation/$char',
    getParentRoute: () => CoursLettresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercice': typeof ExerciceRouteWithChildren
  '/exercice-intro': typeof ExerciceIntroRoute
  '/exercice-liste': typeof ExerciceListeRoute
  '/profil': typeof ProfilRoute
  '/accueil': typeof AppAccueilRoute
  '/bibliotheque': typeof AppBibliothequeRoute
  '/communaute': typeof AppCommunauteRoute
  '/mon-profil': typeof AppMonProfilRoute
  '/plus': typeof AppPlusRoute
  '/reglages': typeof AppReglagesRoute
  '/cours/$family': typeof CoursFamilyRoute
  '/cours/lettres': typeof CoursLettresRouteWithChildren
  '/cours/lettres/$char': typeof CoursLettresCharRoute
  '/cours/mots/$groupId': typeof CoursMotsGroupIdRoute
  '/cours/syllabes/$consonant': typeof CoursSyllabesConsonantRoute
  '/exercice/lettre/$char': typeof ExerciceLettreCharRoute
  '/exercice/mots-croises/$puzzleId': typeof ExerciceMotsCroisesPuzzleIdRoute
  '/exercice/mots/$groupId': typeof ExerciceMotsGroupIdRoute
  '/exercice/syllabes/$consonant': typeof ExerciceSyllabesConsonantRoute
  '/cours/lettres/formation/$char': typeof CoursLettresFormationCharRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercice': typeof ExerciceRouteWithChildren
  '/exercice-intro': typeof ExerciceIntroRoute
  '/exercice-liste': typeof ExerciceListeRoute
  '/profil': typeof ProfilRoute
  '/accueil': typeof AppAccueilRoute
  '/bibliotheque': typeof AppBibliothequeRoute
  '/communaute': typeof AppCommunauteRoute
  '/mon-profil': typeof AppMonProfilRoute
  '/plus': typeof AppPlusRoute
  '/reglages': typeof AppReglagesRoute
  '/cours/$family': typeof CoursFamilyRoute
  '/cours/lettres': typeof CoursLettresRouteWithChildren
  '/cours/lettres/$char': typeof CoursLettresCharRoute
  '/cours/mots/$groupId': typeof CoursMotsGroupIdRoute
  '/cours/syllabes/$consonant': typeof CoursSyllabesConsonantRoute
  '/exercice/lettre/$char': typeof ExerciceLettreCharRoute
  '/exercice/mots-croises/$puzzleId': typeof ExerciceMotsCroisesPuzzleIdRoute
  '/exercice/mots/$groupId': typeof ExerciceMotsGroupIdRoute
  '/exercice/syllabes/$consonant': typeof ExerciceSyllabesConsonantRoute
  '/cours/lettres/formation/$char': typeof CoursLettresFormationCharRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/exercice': typeof ExerciceRouteWithChildren
  '/exercice-intro': typeof ExerciceIntroRoute
  '/exercice-liste': typeof ExerciceListeRoute
  '/profil': typeof ProfilRoute
  '/_app/accueil': typeof AppAccueilRoute
  '/_app/bibliotheque': typeof AppBibliothequeRoute
  '/_app/communaute': typeof AppCommunauteRoute
  '/_app/mon-profil': typeof AppMonProfilRoute
  '/_app/plus': typeof AppPlusRoute
  '/_app/reglages': typeof AppReglagesRoute
  '/cours/$family': typeof CoursFamilyRoute
  '/cours/lettres': typeof CoursLettresRouteWithChildren
  '/cours/lettres/$char': typeof CoursLettresCharRoute
  '/cours/mots/$groupId': typeof CoursMotsGroupIdRoute
  '/cours/syllabes/$consonant': typeof CoursSyllabesConsonantRoute
  '/exercice/lettre/$char': typeof ExerciceLettreCharRoute
  '/exercice/mots-croises/$puzzleId': typeof ExerciceMotsCroisesPuzzleIdRoute
  '/exercice/mots/$groupId': typeof ExerciceMotsGroupIdRoute
  '/exercice/syllabes/$consonant': typeof ExerciceSyllabesConsonantRoute
  '/cours/lettres/formation/$char': typeof CoursLettresFormationCharRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercice'
    | '/exercice-intro'
    | '/exercice-liste'
    | '/profil'
    | '/accueil'
    | '/bibliotheque'
    | '/communaute'
    | '/mon-profil'
    | '/plus'
    | '/reglages'
    | '/cours/$family'
    | '/cours/lettres'
    | '/cours/lettres/$char'
    | '/cours/mots/$groupId'
    | '/cours/syllabes/$consonant'
    | '/exercice/lettre/$char'
    | '/exercice/mots-croises/$puzzleId'
    | '/exercice/mots/$groupId'
    | '/exercice/syllabes/$consonant'
    | '/cours/lettres/formation/$char'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercice'
    | '/exercice-intro'
    | '/exercice-liste'
    | '/profil'
    | '/accueil'
    | '/bibliotheque'
    | '/communaute'
    | '/mon-profil'
    | '/plus'
    | '/reglages'
    | '/cours/$family'
    | '/cours/lettres'
    | '/cours/lettres/$char'
    | '/cours/mots/$groupId'
    | '/cours/syllabes/$consonant'
    | '/exercice/lettre/$char'
    | '/exercice/mots-croises/$puzzleId'
    | '/exercice/mots/$groupId'
    | '/exercice/syllabes/$consonant'
    | '/cours/lettres/formation/$char'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/exercice'
    | '/exercice-intro'
    | '/exercice-liste'
    | '/profil'
    | '/_app/accueil'
    | '/_app/bibliotheque'
    | '/_app/communaute'
    | '/_app/mon-profil'
    | '/_app/plus'
    | '/_app/reglages'
    | '/cours/$family'
    | '/cours/lettres'
    | '/cours/lettres/$char'
    | '/cours/mots/$groupId'
    | '/cours/syllabes/$consonant'
    | '/exercice/lettre/$char'
    | '/exercice/mots-croises/$puzzleId'
    | '/exercice/mots/$groupId'
    | '/exercice/syllabes/$consonant'
    | '/cours/lettres/formation/$char'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ExerciceRoute: typeof ExerciceRouteWithChildren
  ExerciceIntroRoute: typeof ExerciceIntroRoute
  ExerciceListeRoute: typeof ExerciceListeRoute
  ProfilRoute: typeof ProfilRoute
  CoursFamilyRoute: typeof CoursFamilyRoute
  CoursLettresRoute: typeof CoursLettresRouteWithChildren
  CoursMotsGroupIdRoute: typeof CoursMotsGroupIdRoute
  CoursSyllabesConsonantRoute: typeof CoursSyllabesConsonantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercice-liste': {
      id: '/exercice-liste'
      path: '/exercice-liste'
      fullPath: '/exercice-liste'
      preLoaderRoute: typeof ExerciceListeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercice-intro': {
      id: '/exercice-intro'
      path: '/exercice-intro'
      fullPath: '/exercice-intro'
      preLoaderRoute: typeof ExerciceIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercice': {
      id: '/exercice'
      path: '/exercice'
      fullPath: '/exercice'
      preLoaderRoute: typeof ExerciceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/lettres': {
      id: '/cours/lettres'
      path: '/cours/lettres'
      fullPath: '/cours/lettres'
      preLoaderRoute: typeof CoursLettresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/$family': {
      id: '/cours/$family'
      path: '/cours/$family'
      fullPath: '/cours/$family'
      preLoaderRoute: typeof CoursFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reglages': {
      id: '/_app/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof AppReglagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plus': {
      id: '/_app/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof AppPlusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mon-profil': {
      id: '/_app/mon-profil'
      path: '/mon-profil'
      fullPath: '/mon-profil'
      preLoaderRoute: typeof AppMonProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communaute': {
      id: '/_app/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof AppCommunauteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bibliotheque': {
      id: '/_app/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AppBibliothequeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accueil': {
      id: '/_app/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AppAccueilRouteImport
      parentRoute: typeof AppRoute
    }
    '/exercice/syllabes/$consonant': {
      id: '/exercice/syllabes/$consonant'
      path: '/syllabes/$consonant'
      fullPath: '/exercice/syllabes/$consonant'
      preLoaderRoute: typeof ExerciceSyllabesConsonantRouteImport
      parentRoute: typeof ExerciceRoute
    }
    '/exercice/mots/$groupId': {
      id: '/exercice/mots/$groupId'
      path: '/mots/$groupId'
      fullPath: '/exercice/mots/$groupId'
      preLoaderRoute: typeof ExerciceMotsGroupIdRouteImport
      parentRoute: typeof ExerciceRoute
    }
    '/exercice/mots-croises/$puzzleId': {
      id: '/exercice/mots-croises/$puzzleId'
      path: '/mots-croises/$puzzleId'
      fullPath: '/exercice/mots-croises/$puzzleId'
      preLoaderRoute: typeof ExerciceMotsCroisesPuzzleIdRouteImport
      parentRoute: typeof ExerciceRoute
    }
    '/exercice/lettre/$char': {
      id: '/exercice/lettre/$char'
      path: '/lettre/$char'
      fullPath: '/exercice/lettre/$char'
      preLoaderRoute: typeof ExerciceLettreCharRouteImport
      parentRoute: typeof ExerciceRoute
    }
    '/cours/syllabes/$consonant': {
      id: '/cours/syllabes/$consonant'
      path: '/cours/syllabes/$consonant'
      fullPath: '/cours/syllabes/$consonant'
      preLoaderRoute: typeof CoursSyllabesConsonantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/mots/$groupId': {
      id: '/cours/mots/$groupId'
      path: '/cours/mots/$groupId'
      fullPath: '/cours/mots/$groupId'
      preLoaderRoute: typeof CoursMotsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/lettres/$char': {
      id: '/cours/lettres/$char'
      path: '/$char'
      fullPath: '/cours/lettres/$char'
      preLoaderRoute: typeof CoursLettresCharRouteImport
      parentRoute: typeof CoursLettresRoute
    }
    '/cours/lettres/formation/$char': {
      id: '/cours/lettres/formation/$char'
      path: '/formation/$char'
      fullPath: '/cours/lettres/formation/$char'
      preLoaderRoute: typeof CoursLettresFormationCharRouteImport
      parentRoute: typeof CoursLettresRoute
    }
  }
}

interface AppRouteChildren {
  AppAccueilRoute: typeof AppAccueilRoute
  AppBibliothequeRoute: typeof AppBibliothequeRoute
  AppCommunauteRoute: typeof AppCommunauteRoute
  AppMonProfilRoute: typeof AppMonProfilRoute
  AppPlusRoute: typeof AppPlusRoute
  AppReglagesRoute: typeof AppReglagesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccueilRoute: AppAccueilRoute,
  AppBibliothequeRoute: AppBibliothequeRoute,
  AppCommunauteRoute: AppCommunauteRoute,
  AppMonProfilRoute: AppMonProfilRoute,
  AppPlusRoute: AppPlusRoute,
  AppReglagesRoute: AppReglagesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ExerciceRouteChildren {
  ExerciceLettreCharRoute: typeof ExerciceLettreCharRoute
  ExerciceMotsCroisesPuzzleIdRoute: typeof ExerciceMotsCroisesPuzzleIdRoute
  ExerciceMotsGroupIdRoute: typeof ExerciceMotsGroupIdRoute
  ExerciceSyllabesConsonantRoute: typeof ExerciceSyllabesConsonantRoute
}

const ExerciceRouteChildren: ExerciceRouteChildren = {
  ExerciceLettreCharRoute: ExerciceLettreCharRoute,
  ExerciceMotsCroisesPuzzleIdRoute: ExerciceMotsCroisesPuzzleIdRoute,
  ExerciceMotsGroupIdRoute: ExerciceMotsGroupIdRoute,
  ExerciceSyllabesConsonantRoute: ExerciceSyllabesConsonantRoute,
}

const ExerciceRouteWithChildren = ExerciceRoute._addFileChildren(
  ExerciceRouteChildren,
)

interface CoursLettresRouteChildren {
  CoursLettresCharRoute: typeof CoursLettresCharRoute
  CoursLettresFormationCharRoute: typeof CoursLettresFormationCharRoute
}

const CoursLettresRouteChildren: CoursLettresRouteChildren = {
  CoursLettresCharRoute: CoursLettresCharRoute,
  CoursLettresFormationCharRoute: CoursLettresFormationCharRoute,
}

const CoursLettresRouteWithChildren = CoursLettresRoute._addFileChildren(
  CoursLettresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ExerciceRoute: ExerciceRouteWithChildren,
  ExerciceIntroRoute: ExerciceIntroRoute,
  ExerciceListeRoute: ExerciceListeRoute,
  ProfilRoute: ProfilRoute,
  CoursFamilyRoute: CoursFamilyRoute,
  CoursLettresRoute: CoursLettresRouteWithChildren,
  CoursMotsGroupIdRoute: CoursMotsGroupIdRoute,
  CoursSyllabesConsonantRoute: CoursSyllabesConsonantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
